spring:
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}
  liquibase:
    enabled: false
  cloud:
    vault:
      generic:
        enabled: true
        profile-separator: '/'
        default-context: hackathon-read-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  application:
    name: hackathon-read-service
server:
  port: 0
